### ISSUE TITLE
Too many frozen variables

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#17]
For the simple input program:
```
{a;b}.
:- a, not b.
:- b, not a.

```
the behaviour of clingo and clingo-dl seems different.
Der Aufruf:
`clingo-dl --stats=2 --sat-prepro 0` liefert unter anderem:
```
Tight        : Yes
Variables    : 2        (Eliminated:    0 Frozen:    2)
Constraints  : 2        (Binary: 100.0% Ternary:   0.0% Other:   0.0%)
```

Der Aufruf:
`clingo --stats=2 --sat-prepro 0` liefert unter anderem:
```
Tight        : Yes
Variables    : 2        (Eliminated:    1 Frozen:    0)
Constraints  : 0        (Binary:   0.0% Ternary:   0.0% Other:   0.0%
```

It seems that (nearly) all variables are always frozen and none are eliminated.

**Comment by rkaminsk** [comment]
This is no bug. clingo-dl uses clingo's theory interface. In this mode, clingo makes sure that the program can be extended so more variables are frozen.

**Comment by MaxOstrowski** [comment]
Although there are no theory variables in this example and this is clearly an equivalence ?

**Comment by rkaminsk** [comment]
I cannot tell you the details but I believe that in incremental mode most variables are frozen. You would have to as @BenKaufmann for more information.

**Comment by MaxOstrowski** [comment]
I would agree on the problem with the incremental mode. If for example the equivalence is true under a certain assumption. But I can not see any case where this equivalence becomes invalid.
You are right, maybe @BenKaufmann knows more.

**Comment by MaxOstrowski** [comment]
Just as a follow up, we managed to reproduce this with clingo with the following program:
```
#script (python)
import clingo

def main(prg):
    prg.configuration.solve.models = 0
    prg.ground([("base", [])])
    prg.solve()

#end.

{a;b}.
:- a, not b.
:- b, not a.
```
and we guess that we understand why this decision was made.
But maybe one of the experts has some splendid ideas on this how to still enable sat preprocessing on such programs.

**Comment by rkaminsk** [comment]
> I would agree on the problem with the incremental mode. If for example the equivalence is true under a certain assumption. But I can not see any case where this equivalence becomes invalid.
> You are right, maybe @BenKaufmann knows more.

Sometimes, developing a certain feature means having to spend a lot more effort. Just look at the compromises you made in your recent clingo-dl patch...

**Comment by MaxOstrowski** [comment]
Sure, I did not mean to do any criticism here. I just wondered if this was:
a) intentional
b) maybe easy to fix/enhance.
The question is actually driven by some real application using clingo-dl, where half of the constraints are actually used to describe equivalences of variables. Developing an encoding that does not introduce these variables in the first place is also possible, but removes a lot of declarativeness and maintainability.
So maybe we could reopen this issue on "clingo" as a feature request? (once maybe Benjamin has responded)

**Comment by BenKaufmann** [comment]
Hi,

in general, the reason for this behaviour is historic. Remember that clasp predates the logic + control era. It started as single-shot CDNL solver with quite complex ASP preprocessing. 
When we first added support for incremental solving (i.e. the first iclingo), we did not invest too much time into incremental preprocessing but instead only limited its scope. 
I guess the reason for this was complexity vs. usefulness. On the one hand, even if you only allow modular programs, variable-elimination is non-trivial for incremental programs because variables can reoccur in rule bodies. In that case, you have to be able to (recursively) _uneliminate_ variables, which typically means that you have to remember (a subset of) clauses over such variables. In clasp, this is complicated by the fact that the atoms (and rules) of the logic program and the final solver variables (and constraints) are different entities. On the other hand, there were not many incremental programs.

The reason for the observed behaviour in this specific case has more to do with interfaces, though.
To keep complexity low, we only support a coarse-grained high-level interface between clingo and clasp. For example, we only distinguish between single-shot and multi-shot. The latter is active as soon as there is some script with a main function. Hence, in this case clasp is oblivious to the fact that `a` and/or `b` won't reoccur and are therefore candidates for elimination.

**Comment by BenKaufmann** [comment]
@MaxOstrowski 
Sorry, I missed your comment while typing my first answer.  Regarding your last questions, I'd say
a) yes
b) no.
From the perspective of clasp, everything regarding preprocessing is unfortunately intricate. But maybe there is an easy was to add equivalences  without relying on preprocessing.

**Comment by rkaminsk** [comment]
It might be possible to add an option to start clingo in single-shot mode. But this would be one of those very difficult to document options because the API can only be used in limited ways if activated. Also, this might or might not be enough for clingo-dl. There are issues, like is the logic program/theory data still available while the propagator is initialized, to consider. You can add a feature request for this with clingo. But I cannot give you an ETA. A feature request for an incremental sat-preprocessor would belong in clasp's issue tracker. Closing this here.
