### ISSUE TITLE
New Sorting heuristic

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoDL#27]
Sorting edges before propagation/consistency check.
Not only taking the weight w of edges into account but also the potential x = p_1 + w -p_2.
Sorting once could be sufficient, resorting could be better but costly.

**Comment by MaxOstrowski** [comment]
[results.zip](https://github.com/potassco/clingoDL/files/4313159/results.zip)
Comparison of weight, potential and inverse_potential heuristics.
Does not do too much I think, still follow up ?
@rkaminsk

**Comment by rkaminsk** [comment]
The `clingodl-hash/setting-b4ae766` and `clingodl-hash/setting-b4ae766-weight` columns look like they are the same minus noise. Otherwise, it looks like we might want to keep the sort by potential configuration. Propagation does not seem to help as usual. Can you do another test of the three configurations:

- no sorting
- sort by weight
- sort by potential

You should also check that they are different by comparing the choice/conflict counts and instances that did not timeout.

**Comment by MaxOstrowski** [comment]
Sorry, sort by weight was the default, so we do not had no sorting.

**Comment by rkaminsk** [comment]
This explains the results because last time we had 16 timeouts without sorting.

**Comment by MaxOstrowski** [comment]
OK,
`--sort-edges=potential`
and
`--sort-edges=potential-reversed`
are exactly the same behaviour, as common command line parsing only considers the first matching part of the string :(

**Comment by rkaminsk** [comment]
> OK,
> `--sort-edges=potential`
> and
> `--sort-edges=potential-reversed`
> are exactly the same behaviour, as common command line parsing only considers the first matching part of the string :(

This is not true. For the value a custom parser is used, which can be implemented any way you like.

**Comment by MaxOstrowski** [comment]
The one timeout difference is somehow very weird.
instances/flow_shop/tai100_20_2.lp
potential_reversed seemed to have reported a timeout although it has the same conflicts/choices as -potential (which should behave EXACTLY the same) and is set to be 700s slower.
Unfortunately I  have already overwritten the statistics files :(

**Comment by MaxOstrowski** [comment]
> This is not true. For the value a custom parser is used, which can be implemented any way you like.

The common command line parsing I copied from the propagation mode :) I already fixed that. The other bug bothers me more :(

**Comment by MaxOstrowski** [comment]
[results.zip](https://github.com/potassco/clingoDL/files/4318650/results.zip)
And again, this time *hopefully* more reliable. But also more indistinguishable.

**Comment by rkaminsk** [comment]
You are not calculating the potential correctly. For an edge `u -> v` It should be calculated as:
```cpp
u.potential() + uv.weight - v.potential()
```
Because if this value is smaller than zero, then add_edge will have to do work (just have a look add the beginning of the `add_edge` function). Also you can make the code nicer by implementing a `get_potential(uv_idx)` function, which you can then use in the lambda.

**Comment by MaxOstrowski** [comment]
I thought that this is exactly what I'm doing.
`auto costl = (g.node_value_defined(le.from) ? -g.node_value(le.from) : 0) + le.weight + (g.node_value_defined(le.to) ? -g.node_value(le.to) : 0);`
As potential() is not easily accesible for me I decided to use node_value
`T node_value(int idx) const { return -nodes_[idx].potential(); }`
which returns the negative potential.
I still have to subtract the v.potential(), fixed this now. Could you have a look if this is now the correct formula?
I will clean this up once we have decided which part stays...

**Comment by rkaminsk** [comment]
> Could you have a look if this is now the correct formula?

It looks correct to me like this.

**Comment by MaxOstrowski** [comment]
Aaaaaand here we go again....
[results.zip](https://github.com/potassco/clingoDL/files/4324386/results.zip)

Btw: I just observed that -propagation=inverse has quite some overhead alone on many benchmarks where it actually does not propagate a thing.

**Comment by rkaminsk** [comment]
> Aaaaaand here we go again....
> [results.zip](https://github.com/potassco/clingoDL/files/4324386/results.zip)

It is interesting that the reversed potential performs best. Maybe we should also try the weights reversed?

> Btw: I just observed that -propagation=inverse has quite some overhead alone on many benchmarks where it actually does not propagate a thing.

Maybe because of the candidate edge tracking.

**Comment by rkaminsk** [comment]
> The common command line parsing I copied from the propagation mode :) I already fixed that. The other bug bothers me more :(

It is still not correct. Like this it will ignore anything that follows a match. In this case you can also make the option thread-specific like the other ones.

**Comment by MaxOstrowski** [comment]
Made them thread specific and added lambdas to clean the code.
Nevertheless, the benchmarks should have been correct, right ?
Which leads to the question, what will be the new default.
Taking this to a PR.

**Comment by rkaminsk** [comment]
Have you seen my other comment about reversing the order for weights?

**Comment by MaxOstrowski** [comment]
Ups, no, missed this one.

**Comment by MaxOstrowski** [comment]
[results.zip](https://github.com/potassco/clingoDL/files/4336867/results.zip)

Did I something wrong again, or are the benchmarks just showing random results.

**Comment by rkaminsk** [comment]
Why do you say this? It is kind of what I would have expected. The new values are similar to potential reversed. Interestingly reversing the sorting really seems to be better than doing it the other way round.

Otherwise, I remember Marius saying that on the old cluster you can have very high runtime fluctuations, which get worse the more things you run in parallel on a node. Now, I do not know how you ran the benchmarks. But a configuration that should get you clean results, is running on the kr partition of the cluster with just one job per node. It will take a little longer though. About 10h I would think.

To me it looks like we should certainly keep the potential/reversed configuration. Probably, we can just keep all of them because it is very easy to support them all.

**Comment by MaxOstrowski** [comment]
Sorry, it was not about the fluctuation. The benchmarks ran with cpt=4, which on old zuse did exactly what you describe.
I was talking about the reverse things, also weight-reverse seems to be quite good.
Weirdly, weight and weight-reversed both are better than just not sorting at all. And this is something that does not make sense to me. Same for potential.
